# Generated by Django 3.2.4 on 2021-06-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0007_pessoa_telefones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='telefones',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Telefone',
        ),
    ]
