# Generated by Django 3.2.3 on 2021-06-30 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0009_departamento_pessoa_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('nivel', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meuapp.cargo'),
        ),
    ]
