# Generated by Django 3.2.3 on 2021-06-30 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0010_auto_20210630_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='plantao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meuapp.plantao'),
        ),
    ]
