# Generated by Django 3.2.3 on 2021-06-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0011_auto_20210630_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantao',
            name='horario',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plantao',
            name='nome',
            field=models.CharField(default='Normal', max_length=20),
        ),
    ]
